# Generated by Django 6.0.5 on 2026-10-02 15:08

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the class/batch', max_length=120, unique=True)),
                ('code', models.CharField(blank=True, help_text='Short code or identifier (e.g. C10-A)', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Optional description or notes about this class')),
                ('is_active', models.BooleanField(default=True, help_text='Active classes will appear in the portal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Class / Batch',
                'verbose_name_plural': 'Classes / Batches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the mock test (e.g. Science Mock Test 1)', max_length=255)),
                ('code', models.CharField(blank=True, help_text='Exam code (e.g., MT-SCI-01)', max_length=50)),
                ('subject', models.CharField(blank=True, help_text='Subject or Category (e.g., Mathematics, Physics)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Short description or syllabus of the exam')),
                ('instructions', models.TextField(blank=True, default='1. All questions are Multiple Choice Questions (MCQ).\n2. Select the most appropriate option for each question.\n3. You can review and change your answers before final submission.\n4. There is no restriction to attempt the exam; you can retake it anytime.\n5. After submitting, your detailed result and verification report will be displayed immediately.', help_text='Instructions displayed to students before starting')),
                ('duration_minutes', models.PositiveIntegerField(default=30, help_text='Duration in minutes. Enter 0 for unlimited time.')),
                ('passing_percentage', models.DecimalField(decimal_places=2, default=Decimal('40.00'), help_text='Minimum percentage required to pass', max_digits=5)),
                ('negative_marking', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default negative marks deducted per wrong question (e.g. 0.25 or 0)', max_digits=4)),
                ('shuffle_questions', models.BooleanField(default=False, help_text='If enabled, questions will appear in randomized order for each attempt')),
                ('is_active', models.BooleanField(default=True, help_text='Only active exams are visible on the public portal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classes', models.ManyToManyField(help_text='Select the class(es) eligible to take this exam', related_name='exams', to='portal.academicclass')),
            ],
            options={
                'verbose_name': 'Mock Test / Exam',
                'verbose_name_plural': 'Mock Tests / Exams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order sequence')),
                ('question_text', models.TextField(help_text='Question text or prompt')),
                ('question_image', models.ImageField(blank=True, help_text='Optional diagram/image', null=True, upload_to='questions/')),
                ('option_a', models.TextField(verbose_name='Option A')),
                ('option_b', models.TextField(verbose_name='Option B')),
                ('option_c', models.TextField(verbose_name='Option C')),
                ('option_d', models.TextField(verbose_name='Option D')),
                ('correct_option', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], help_text='The correct answer option (A, B, C, or D)', max_length=1)),
                ('marks', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Marks awarded for correct answer', max_digits=5)),
                ('negative_marks', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Marks deducted for incorrect answer (0 for no penalty)', max_digits=5)),
                ('explanation', models.TextField(blank=True, help_text='Detailed solution/explanation revealed after test submission')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='portal.exam', verbose_name='Mock Test')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Student's full name", max_length=150)),
                ('roll_number', models.CharField(help_text='Roll number or student ID', max_length=50)),
                ('phone', models.CharField(blank=True, help_text='Optional contact number', max_length=25)),
                ('email', models.EmailField(blank=True, help_text='Optional email address', max_length=254)),
                ('is_active', models.BooleanField(default=True, help_text='Active students can take exams')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='portal.academicclass', verbose_name='Class')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['student_class__name', 'name'],
                'unique_together': {('student_class', 'roll_number')},
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(default=1, help_text='Attempt sequence number (1st, 2nd, etc.)')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('wrong_answers', models.PositiveIntegerField(default=0)),
                ('unattempted_answers', models.PositiveIntegerField(default=0)),
                ('score_obtained', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('max_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('is_passed', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='portal.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='portal.student')),
            ],
            options={
                'verbose_name': 'Exam Attempt',
                'verbose_name_plural': 'Exam Attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(blank=True, help_text='A, B, C, D or None if skipped', max_length=1, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('marks_awarded', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='portal.examattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_answers', to='portal.question')),
            ],
            options={
                'verbose_name': 'Attempt Answer',
                'verbose_name_plural': 'Attempt Answers',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
