# Generated by Django 6.0.5 on 2026-10-03 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Subject Name (e.g., Mathematics, Science, Physics)', max_length=120)),
                ('code', models.CharField(blank=True, help_text='Short Subject Code (e.g., MATH, SCI)', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Optional description or syllabus')),
                ('is_active', models.BooleanField(default=True, help_text='Active subjects are available for scheduling')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='portal.academicclass', verbose_name='Class')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['academic_class__name', 'name'],
                'unique_together': {('academic_class', 'name')},
            },
        ),
    ]
